name: Backup Website

on:
  schedule:
    # Esto ejecutará la copia de seguridad todos los días a las 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo desde GitHub Actions

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a backup directory
        run: mkdir -p backup

      - name: Copy website files to backup directory excluding backup folder
        run: |
          rsync -av --exclude 'backup/' ./ backup/

      - name: Add .gitignore entry for backup directory
        run: |
          echo "backup/" >> .gitignore || true

      - name: Commit and push changes
        run: |
          git config --global user.name 'terruno'
          git config --global user.email 'haritz@terrezu.com'

          # Commit de .gitignore
          git add .gitignore
          git commit -m "Ignore backup directory in version control" || echo "No changes to commit"
          git push https://$GH_TOKEN@github.com/terruno/terru-o.git HEAD:main

          # Commit de la carpeta backup
          git add backup/*
          git commit -m "Backup of website" || echo "No changes to commit"
          git push https://$GH_TOKEN@github.com/terruno/mi-repositorio-backup.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
