name: Backup Website

on:
  schedule:
    # Esto ejecutará la copia de seguridad todos los días a las 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo desde la interfaz de GitHub

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a backup directory
        run: mkdir -p backup

      - name: Copy website files to backup directory
        run: |
          rsync -av --exclude 'backup/' ./ backup/

      - name: Commit and push backup to backup repository
        run: |
          git config --global user.name 'terruno'
          git config --global user.email 'haritz@terrezu.com'
          git add backup/*
          git commit -m "Backup of website"
          git push https://github.com/terruno/mi-repositorio-backup.git
          git push https://$GH_TOKEN@github.com/tuusuario/mi-repositorio-backup.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
