name: Backup Website

on:
  schedule:
    - cron: '0 2 * * *'  # Cada día a las 2:00 AM UTC
  workflow_dispatch:      # Permite ejecutarlo manualmente también

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a dated backup directory
        run: |
          DATE=$(date +'%Y-%m-%d')
          mkdir -p backup/$DATE

      - name: Copy website files to dated backup directory excluding backup folder and git internals
        run: |
          DATE=$(date +'%Y-%m-%d')
          rsync -av --exclude 'backup/' --exclude '.git/' --exclude '.github/' --exclude '.gitignore' ./ backup/$DATE/

      - name: Delete backups older than 30 days
        run: |
          find backup/ -maxdepth 1 -type d -name '20*' -mtime +30 -exec rm -rf {} +

      - name: Initialize and push backup repository
        run: |
          cd backup
          git init
          git config --global user.name 'terruno'
          git config --global user.email 'haritz@terrezu.com'
          git remote add origin https://$GH_TOKEN@github.com/terruno/mi-repositorio-backup.git
          git add .
          git commit -m "Backup of website on $(date)"
          git branch -M main
          git push -f origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
