name: Backup Website

on:
  schedule:
    - cron: '0 2 * * *'  # Cada día a las 2:00 AM UTC
  workflow_dispatch:      # También se puede ejecutar manualmente

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio principal
        uses: actions/checkout@v2

      - name: Definir fecha actual
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Crear carpeta de backup con la fecha
        run: mkdir -p backup/${{ env.DATE }}

      - name: Copiar archivos (excluyendo carpetas internas)
        run: |
          rsync -av \
            --exclude 'backup/' \
            --exclude '.git/' \
            --exclude '.github/' \
            --exclude '.gitignore' \
            ./ backup/${{ env.DATE }}/

      - name: Borrar backups de más de 30 días
        run: |
          find backup/ -maxdepth 1 -type d -name '20*' -mtime +30 -exec rm -rf {} +

      - name: Clonar repositorio de respaldo
        run: |
          REPO_URL="https://${GH_TOKEN}@github.com/terruno/mi-repositorio-backup.git"
          git clone "$REPO_URL" backup-repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Copiar nuevos backups al repositorio de respaldo
        run: rsync -av backup/ backup-repo/backup/

      - name: Confirmar y subir cambios
        run: |
          cd backup-repo
          git config user.name 'terruno'
          git config user.email 'haritz@terrezu.com'
          git add .
          git commit -m "Backup on ${{ env.DATE }}" || echo "Sin cambios para confirmar"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}


