name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama donde trabajas

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload site
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Aquí puedes poner "dist" o el directorio de salida si usas build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
